In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [2]:
data = sklearn.datasets.load_breast_cancer()

In [3]:
print(data)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [4]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [5]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [6]:
df["label"] = data.target

In [7]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  label  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [8]:
df.shape

(569, 31)

In [9]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [10]:
df['label'].value_counts()

1    357
0    212
Name: label, dtype: int64

In [11]:
X = df.drop(columns='label',axis =1)
y = df['label']

In [12]:
print(X)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

In [13]:
X = np.asarray(X)
y = np.asarray(y)

In [14]:
print(X)
print(y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 

GridSearchCV

In [15]:
model = SVC()

In [16]:
#hyperparameters
parameters = {
    'kernel' : ['linear','poly','rbf','sigmoid'],
    'C' : [1,5,10,20]
}

In [17]:
#gridsearch
classifier = GridSearchCV(model,parameters,cv=5)

In [18]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [19]:
classifier.cv_results_

{'mean_fit_time': array([2.48729544e+00, 3.82323265e-03, 5.79328537e-03, 1.49131775e-02,
        2.73677239e+00, 3.92251015e-03, 5.16023636e-03, 1.38329983e-02,
        4.08417544e+00, 4.18095589e-03, 5.24954796e-03, 1.36165619e-02,
        6.60717902e+00, 4.33311462e-03, 4.92897034e-03, 1.39028072e-02]),
 'mean_score_time': array([0.00116105, 0.00104527, 0.00202317, 0.00390382, 0.00089488,
        0.00097775, 0.00168476, 0.00337253, 0.0008822 , 0.00095272,
        0.0014997 , 0.00327325, 0.00087104, 0.00092087, 0.00146604,
        0.00330896]),
 'mean_test_score': array([0.94553641, 0.90866325, 0.91217202, 0.46044093, 0.95081509,
        0.92272939, 0.93150132, 0.41117839, 0.95256948, 0.920975  ,
        0.92271386, 0.40239093, 0.9490607 , 0.91922062, 0.92094395,
        0.39886664]),
 'param_C': masked_array(data=[1, 1, 1, 1, 5, 5, 5, 5, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False

In [22]:
best_parameters = classifier.best_params_
print(best_parameters)

{'C': 10, 'kernel': 'linear'}


In [23]:
highest_acc = classifier.best_score_
print(highest_acc)

0.9525694767893185


In [20]:
results = pd.DataFrame(classifier.cv_results_)

In [21]:
results.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       2.487295      1.443406         0.001161        0.000306       1   
1       0.003823      0.000117         0.001045        0.000071       1   
2       0.005793      0.000150         0.002023        0.000048       1   
3       0.014913      0.000278         0.003904        0.000174       1   
4       2.736772      0.548819         0.000895        0.000045       5   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.947368   
1         poly     {'C': 1, 'kernel': 'poly'}           0.842105   
2          rbf      {'C': 1, 'kernel': 'rbf'}           0.850877   
3      sigmoid  {'C': 1, 'kernel': 'sigmoid'}           0.543860   
4       linear   {'C': 5, 'kernel': 'linear'}           0.947368   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.929825           0.973684           0.921053           0.955752   
1           0.885965           0.929825           0.947368           0.938053   
2           0.894737           0.929825           0.947368           0.938053   
3           0.456140           0.464912           0.385965           0.451327   
4           0.938596           0.973684           0.929825           0.964602   

   mean_test_score  std_test_score  rank_test_score  
0         0.945536        0.018689                4  
1         0.908663        0.039382               12  
2         0.912172        0.035444               11  
3         0.460441        0.050253               13  
4         0.950815        0.016216                2

In [24]:
grid_search_results = results[['param_C','param_kernel','mean_test_score']]

In [26]:
grid_search_results

param_C param_kernel  mean_test_score
0        1       linear         0.945536
1        1         poly         0.908663
2        1          rbf         0.912172
3        1      sigmoid         0.460441
4        5       linear         0.950815
5        5         poly         0.922729
6        5          rbf         0.931501
7        5      sigmoid         0.411178
8       10       linear         0.952569
9       10         poly         0.920975
10      10          rbf         0.922714
11      10      sigmoid         0.402391
12      20       linear         0.949061
13      20         poly         0.919221
14      20          rbf         0.920944
15      20      sigmoid         0.398867

In [27]:
#randomizedsearch
classifier = RandomizedSearchCV(model,parameters,cv=5)

In [28]:
classifier.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [29]:
classifier.cv_results_

{'mean_fit_time': array([5.57703972e-03, 3.95731926e-03, 4.24332619e-03, 1.39585018e-02,
        4.31981983e+00, 1.51443481e-02, 5.69782257e-03, 2.97308469e+00,
        1.38238907e-02, 5.03859520e-03]),
 'mean_score_time': array([0.00153408, 0.00102835, 0.00099711, 0.00337591, 0.00104575,
        0.0036809 , 0.00196495, 0.00087547, 0.00332646, 0.0015089 ]),
 'mean_test_score': array([0.90866325, 0.92272939, 0.920975  , 0.41117839, 0.95256948,
        0.46044093, 0.91217202, 0.95081509, 0.40239093, 0.92094395]),
 'param_C': masked_array(data=[1, 5, 10, 5, 10, 1, 1, 5, 10, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['poly', 'poly', 'poly', 'sigmoid', 'linear', 'sigmoid',
                    'rbf', 'linear', 'sigmoid', 'rbf'],
              mask=[False, False, False, False, False, False, False, False,
                    False, Fal

In [30]:
best_parameters = classifier.best_params_
print(best_parameters)

{'kernel': 'linear', 'C': 10}


In [31]:
highest_acc = classifier.best_score_
print(highest_acc)

0.9525694767893185


In [32]:
results = pd.DataFrame(classifier.cv_results_)

In [33]:
results.head(5)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.005577      0.001080         0.001534        0.000403         poly   
1       0.003957      0.000406         0.001028        0.000094         poly   
2       0.004243      0.000092         0.000997        0.000077         poly   
3       0.013959      0.000533         0.003376        0.000076      sigmoid   
4       4.319820      0.549077         0.001046        0.000247       linear   

  param_C                         params  split0_test_score  \
0       1     {'kernel': 'poly', 'C': 1}           0.842105   
1       5     {'kernel': 'poly', 'C': 5}           0.885965   
2      10    {'kernel': 'poly', 'C': 10}           0.885965   
3       5  {'kernel': 'sigmoid', 'C': 5}           0.491228   
4      10  {'kernel': 'linear', 'C': 10}           0.938596   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.885965           0.929825           0.947368           0.938053   
1           0.912281           0.921053           0.938596           0.955752   
2           0.921053           0.903509           0.938596           0.955752   
3           0.421053           0.421053           0.350877           0.371681   
4           0.938596           0.973684           0.947368           0.964602   

   mean_test_score  std_test_score  rank_test_score  
0         0.908663        0.039382                7  
1         0.922729        0.023689                3  
2         0.920975        0.024701                4  
3         0.411178        0.048578                9  
4         0.952569        0.014200                1

In [34]:
randomized_search_results = results[['param_C','param_kernel','mean_test_score']]

In [35]:
randomized_search_results

param_C param_kernel  mean_test_score
0       1         poly         0.908663
1       5         poly         0.922729
2      10         poly         0.920975
3       5      sigmoid         0.411178
4      10       linear         0.952569
5       1      sigmoid         0.460441
6       1          rbf         0.912172
7       5       linear         0.950815
8      10      sigmoid         0.402391
9      20          rbf         0.920944